### ISSUE TITLE
Calling unknown toggleConnections() function

### ISSUE THREAD

**Issue by andrecasal** [hgraph-os/hGraph#67]
Clicking that third X-with-a-circle-in-the-middle button, calls an unknown `toggleConnections()` function (hGraphMain.js's line 148, see screenshot and respective code below).

![screen shot 2018-07-25 at 12 17 08](https://user-images.githubusercontent.com/22457463/43198082-40cdf504-9005-11e8-8bc2-04b140429b64.png)

```
...
graph = new HGraph(opts);
...
$("#connector_btn").click(function(){
	var t = graph.toggleConnections();
	if(!t){
		$(this).find("span").addClass("toggled");
	} else {
		$(this).find("span").removeClass("toggled");
	}
});
```
`graph` is an instance of HGraph, but I can't find that function on the main `HealthGraph.js` file that defines HGraph.

**Comment by ericbenwa** [comment]
Hi André,

Thanks for finding this.

We've created a few other demos that are more up to date (we should take that demo down):
In this repo, check out /examples/multiuser - this breaks away from needing a UI of buttons to zoom in/out.

Or... try the React component of hGraph we're in the progress of making.
https://github.com/goinvo/hgraph-react

Thanks!
Eric

**Comment by andrecasal** [comment]
Hi Eric,

Got it, thanks for the heads up.

Craig told me about the react component :) Will be useful for Native React.

Thanks,
André

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by craigmcginley** [comment]
@andrecasal just FYI, if you are working in React Native, I'd recommend checking out the port Nabyl is doing over at Citizen Health: https://github.com/CitizenHealth/react-native-hgraph

**Comment by andrecasal** [comment]
Hi Craig,

Thanks, that'll be most useful!

Cheers,
André

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
